lang: nb

project:
  type: website
  output-dir: _site
  # render:
    # - "dashboard/**"
    # - "!projects/**"

website:
  title: ""
  site-url: "https://SVA-OsloMet.github.io/kodebib/"
  navbar:
    logo: assets/logo-oslomet.svg
    left:
      - href: dashboard/index.qmd
        text: Kodebibliotek
      - href: dashboard/faq.qmd
        text: FAQ

format:
  html:
    theme: [cosmo, themes/custom.scss]
      # light: [cosmo, themes/custom.scss]
      # dark: [cosmo, themes/custom-dark.scss]
    css: styles.css
    toc: true

resources:
  - dashboard/projects.json
  - assets/**